"""add product categories

Revision ID: 97db2d7d9a6e
Revises: 
Create Date: 2020-02-21 21:37:03.394743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97db2d7d9a6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category_name'), 'product_category', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_category_name'), table_name='product_category')
    op.drop_table('product_category')
    # ### end Alembic commands ###
